<section id="index">
    <h1>Bienvenido a Adaptike</h1>
    <br/>
    <table class="table" id="index-menu">
        <tr>
            <td><img src="/img/items-icon.png" /></td>
            <td style="padding-top: 20px">
                <b>Banco de Ítems</b>
                <p>Puede administrar los ítems de su banco de ítems usando esta opción. 
                    Para poder ingresar ítems al sistema debe tener al menos una categoría registrada.</p>
                <a href="/admin/items" class="btn pull-right"><i class="icon-arrow-right"></i> Ver banco de ítems</a>
            </td>
        </tr>
        <tr>
            <td><img src="/img/categorias-icon.png" /></td>
            <td style="padding-top: 20px">
                <b>Categorías</b>
                <p>Puede administrar las competencias de su banco de ítems usando esta opción. 
                </p>
                <a href="/admin/categorias" class="btn pull-right"><i class="icon-arrow-right"></i> Ver competencias</a>
            </td>
        </tr>
        <tr>
            <td><img src="/img/test-icon.png" /></td>
            <td style="padding-top: 20px">
                <b>Tests</b>
                <p>Puede crear y ejecutar tests usando esta opción. 
                </p>
                <a href="/admin/tests" class="btn pull-right"><i class="icon-arrow-right"></i> Ver tests</a>
            </td>
        </tr>
        <tr>
            <td><img src="/img/documentation-icon.png" /></td>
            <td style="padding-top: 20px">
                <b>Documentación</b>
                <p>Puede aprender sobre el uso de Adaptike usando esta opción.</p>
                <a href="/admin/docs" class="btn pull-right"><i class="icon-arrow-right"></i> Ver documentación</a>
            </td>
        </tr>
    </table>
</section>