<section id="tests">
    <h2>Crear grupo</h2>
    <hr/>
    <form id="test-form-add" method="post">
        <p>
        <label for="nombre">Nombre del grupo:</label>  
        <input type="text" id="nombre" name="nombre" />
        </p>
        <input type="submit" class="btn btn-primary" id="grupo-add" value="Crear grupo">
        <a href="/admin/grupos" class="btn">Cancelar</a>
    </form>
</section>