<section id="categorias">
    <h2><a href="/admin/grupos">Grupos</a> > Usuarios del grupo</h2>
    <hr/>
    <div id="controls">
        <a href="/admin/grupos/adduser/gid/<?php echo $this->gid?>" class="btn"><i class="icon-plus"></i> Agregar usuario</a>
    </div>
    <br/>
    <table class="table table-striped" id="users-list">
        <tr>
            <th>Nombre completo</th>
            <th>Programa</th>
            <th>Email</th>
            <th>&nbsp;</th>
        </tr>
       <?php foreach($this->grupo[0]['estudiantes'] as $e){ ?>
             <tr>
                <td><?php echo $e['usuario']['nombre'].' '.$e['usuario']['apellido'] ?></td>
                <td><?php echo $e['usuario']['acceso_programas'][0]['nombre'] ?>, <?php echo $e['usuario']['acceso_programas'][0]['institucion']['nombre'] ?></td>
                <td><?php echo $e['usuario']['email'] ?></td>
                <td>&nbsp;</td>
            </tr>
       <?php } ?>
    </table>
</section>