<section id="categorias">
    <h2>Agregar competencia</h2>
    <hr/>
    <form id="categoria-form-add">
        <p>
        <label for="nombrecategoria">Nombre de competencia:</label>  
        <input type="text" id="nombrecategoria" name="nombrecategoria" />
        <label for="categoriapadre">Categoría padre:</label>
        <select id="categoriapadre">
            <option value="0">Seleccione una competencia...</option>
        </select>
        </p>
        <a href="#" class="btn btn-primary" id="categoria-add">Agregar competencia</a>
        <a href="/admin/categorias" class="btn">Cancelar</a>
    </form>
</section>