<section id="categorias">
    <h2>Listado de Competencias</h2>
    <hr/>
    <div id="controls">
        <a href="/admin/categorias/add" class="btn"><i class="icon-plus"></i> Agregar competencia</a>
    </div>
    <br/>
    <table class="table table-striped" id="categorias-list">
        <tr>
            <th>Competencia</th>
            <th>Competencia padre</th>
        </tr>
    </table>
</section>