<h1>Mis estadísticas</h1>
<hr/>
<h3>Mis habilidades</h3>
<table class="table table-striped" id="habilidades">
    <tr>
        <th>Categoría</th>
        <th>Nivel de habilidad actual</th>
    </tr>
</table>
<h3>Mis tests</h3>
<table class="table table-striped" id="tests">
    <tr>
        <th>Fecha del test</th>
        <th>Categoría</th>
        <th>Ítems contestados</th>
        <th>Nivel de habilidad final</th>
    </tr>
</table>